// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASQj3WeOLvluBNSh224sY8UAGUsKGtTXU',
    appId: '1:105543516618:web:40ef496f1463a52e830f33',
    messagingSenderId: '105543516618',
    projectId: 'itaimtour-607f8',
    authDomain: 'itaimtour-607f8.firebaseapp.com',
    storageBucket: 'itaimtour-607f8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQAUV5KgipGTgPJbMy7WGJopdtAsXfxS0',
    appId: '1:105543516618:android:49432c3c86fbdf46830f33',
    messagingSenderId: '105543516618',
    projectId: 'itaimtour-607f8',
    storageBucket: 'itaimtour-607f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0uT8kZYSP7orSNsHs8u6vXWMG3IMpmw4',
    appId: '1:105543516618:ios:6b04b0315ef6a3c1830f33',
    messagingSenderId: '105543516618',
    projectId: 'itaimtour-607f8',
    storageBucket: 'itaimtour-607f8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0uT8kZYSP7orSNsHs8u6vXWMG3IMpmw4',
    appId: '1:105543516618:ios:6b04b0315ef6a3c1830f33',
    messagingSenderId: '105543516618',
    projectId: 'itaimtour-607f8',
    storageBucket: 'itaimtour-607f8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASQj3WeOLvluBNSh224sY8UAGUsKGtTXU',
    appId: '1:105543516618:web:172e2b570572363f830f33',
    messagingSenderId: '105543516618',
    projectId: 'itaimtour-607f8',
    authDomain: 'itaimtour-607f8.firebaseapp.com',
    storageBucket: 'itaimtour-607f8.firebasestorage.app',
  );

}